spring:
  application:
    name: dubbo-comsumer
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
server:
  port: 8081
